name: Manual Approval Workflow

on:
  push:
    branches: [ master ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Build and test your code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          mvn clean package --file pom.xml

  manual_approval:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Create approval issue
      - name: Create approval issue
        run: |
          issue_response=$(gh issue create --title "Manual Approval Required" --body "Please review and approve this workflow run." --assignee "papannah" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}")
          echo "ISSUE_NUMBER=$(echo $issue_response | jq -r '.number')" >> $GITHUB_ENV

      # Step 2: Wait for manual approval
      - name: Wait for approval
        id: approval
        run: |
          echo "Workflow is paused, waiting for manual approval"

  some_other_job:
    needs: manual_approval
    runs-on: ubuntu-latest
    steps:
      # Step 4: Resume the workflow on manual approval
      - name: Close approval issue
        run: |
          gh issue close $ISSUE_NUMBER -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

      # Additional steps after approval if needed

      # Example: Deploy the code
      - name: Deploy
        run: |
          echo "Deployment Done"
