name: Manual Approval Workflow

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Build and test your code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          mvn clean package --file pom.xml

  manual_approval:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Create approval issue
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create approval issue
        id: create_issue
        run: |
          npm install @actions/github
          node ./create_issue.js ${{ secrets.GITHUB_TOKEN }}
        env:
          ISSUE_NUMBER: ${{ steps.create_issue.outputs.issue_number }}

      # Step 2: Wait for manual approval
      - name: Wait for approval
        id: approval
        run: |
          echo "Workflow is paused, waiting for manual approval"

  some_other_job:
    needs: manual_approval
    runs-on: ubuntu-latest
    steps:
      # Step 4: Resume the workflow on manual approval
      - name: Close approval issue
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "state": "closed"
            }' \
            "https://api.github.com/repos/he329178/gitopscalculator/issues/$ISSUE_NUMBER"

      # Additional steps after approval if needed

      # Example: Deploy the code
      - name: Deploy
        run: |
          echo "Deployment Done"
