name: Manual Approval Workflow

on:
  push:
    branches: [ master ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Build and test your code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          mvn clean package --file pom.xml

  manual_approval:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Create approval issue
      - name: Create approval issue
        id: create_issue
        run: |
          response=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "Manual Approval Required",
              "body": "Please review and approve this workflow run.",
              "assignees": ["he329178"]
            }' \
            "https://api.github.com/repos/he329178/gitopscalculator/issues")
          ISSUE_NUMBER=$(echo "$response" | jq -r '.number')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      # Step 2: Wait for manual approval
      - name: Wait for approval
        id: approval
        run: |
          echo "Workflow is paused, waiting for manual approval"

  some_other_job:
    needs: manual_approval
    runs-on: ubuntu-latest
    steps:
      # Step 4: Resume the workflow on manual approval
      - name: Close approval issue
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "state": "closed"
            }' \
            "https://api.github.com/repos/he329178/gitopscalculator/issues/$ISSUE_NUMBER"

      # Additional steps after approval if needed

      # Example: Deploy the code
      - name: Deploy
        run: |
          echo "Deployment Done"
